apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- target:
    kind: Deployment
    name: nrpilot-api
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: development
- target:
    kind: Ingress
    name: nrpilot-api
  patch: |
    - op: replace
      path: /spec/rules/0/host
      value: nrpilot-api-dev.nrp-nautilus.io
    - op: replace
      path: /spec/tls/0/hosts/0
      value: nrpilot-api-dev.nrp-nautilus.io
